In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("final merge_dataset.csv")
df1 = pd.read_csv("twitter_dataset.csv")

print(df.head())
print(df1.head())

                                            sentence    label
0  Warmerthannormal sea surface temperatures are ...    FAVOR
1  We will continue to rely in part on fossil fue...     NONE
2  The actual rise in sea levels measured only 12...     NONE
3  Claims of global warming have been greatly exa...  AGAINST
4  The Intergovernmental Panel on Climate Change ...     NONE
  sentiment                                            message  \
0       NaN  RT @Ashton5SOS: Why are you naked?\nUmm Global...
1       NaN  I find global warming confusing. \nWinds on th...
2     Favor  RT @LisaBloom: We will be the only developed n...
3       NaN  @ThomasARoberts @JamesCarville\npress. #Clinto...
4   Against  RT @SteveSGoddard: Winnipeg might not get abov...

                                          clean_text
0            : Why are you naked? Umm Global warming
1  I find global warming confusing. Winds on this...
2  : We will be the only developed nation in the ...
3  press. Clinton emails. Trump calls global warm...
4  : Winnipeg might not get above 0F for the rest...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2438 entries, 0 to 2437
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  2438 non-null   object
 1   label     2438 non-null   object
dtypes: object(2)
memory usage: 38.2+ KB

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11535 entries, 0 to 11534
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sentiment   7690 non-null   object
 1   message     11535 non-null  object
 2   clean_text  11535 non-null  object
dtypes: object(3)
memory usage: 270.5+ KB

In [ ]:
# In df1 replace Nan By NONE in sentiment column
df1['sentiment'].fillna('NONE', inplace=True)
print(df1.head())

  sentiment                                            message  \
0      NONE  RT @Ashton5SOS: Why are you naked?\nUmm Global...
1      NONE  I find global warming confusing. \nWinds on th...
2     Favor  RT @LisaBloom: We will be the only developed n...
3      NONE  @ThomasARoberts @JamesCarville\npress. #Clinto...
4   Against  RT @SteveSGoddard: Winnipeg might not get abov...

                                          clean_text
0            : Why are you naked? Umm Global warming
1  I find global warming confusing. Winds on this...
2  : We will be the only developed nation in the ...
3  press. Clinton emails. Trump calls global warm...
4  : Winnipeg might not get above 0F for the rest...

/tmp/ipykernel_824/2562769564.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['sentiment'].fillna('NONE', inplace=True)

In [ ]:
# in df1 upper Favor to FAVOR and against to AGAINST in sentiment
df1['sentiment'] = df1['sentiment'].replace({'Favor': 'FAVOR', 'Against': 'AGAINST'})
print(df1.head())

  sentiment                                            message  \
0      NONE  RT @Ashton5SOS: Why are you naked?\nUmm Global...
1      NONE  I find global warming confusing. \nWinds on th...
2     FAVOR  RT @LisaBloom: We will be the only developed n...
3      NONE  @ThomasARoberts @JamesCarville\npress. #Clinto...
4   AGAINST  RT @SteveSGoddard: Winnipeg might not get abov...

                                          clean_text
0            : Why are you naked? Umm Global warming
1  I find global warming confusing. Winds on this...
2  : We will be the only developed nation in the ...
3  press. Clinton emails. Trump calls global warm...
4  : Winnipeg might not get above 0F for the rest...

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11535 entries, 0 to 11534
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sentiment   11535 non-null  object
 1   message     11535 non-null  object
 2   clean_text  11535 non-null  object
dtypes: object(3)
memory usage: 270.5+ KB

In [ ]:
# remane columns in df1 clean_text to sentence and sentiment to label
df1 = df1.rename(columns={'clean_text': 'sentence', 'sentiment': 'label'})
print(df1.head())

     label                                            message  \
0     NONE  RT @Ashton5SOS: Why are you naked?\nUmm Global...
1     NONE  I find global warming confusing. \nWinds on th...
2    FAVOR  RT @LisaBloom: We will be the only developed n...
3     NONE  @ThomasARoberts @JamesCarville\npress. #Clinto...
4  AGAINST  RT @SteveSGoddard: Winnipeg might not get abov...

                                            sentence
0            : Why are you naked? Umm Global warming
1  I find global warming confusing. Winds on this...
2  : We will be the only developed nation in the ...
3  press. Clinton emails. Trump calls global warm...
4  : Winnipeg might not get above 0F for the rest...

In [ ]:
#I want to join both the sentence vertically based on column name and drop excess column
df2 = pd.concat([df, df1], axis=0)
print(df.head())

                                            sentence    label
0  Warmerthannormal sea surface temperatures are ...    FAVOR
1  We will continue to rely in part on fossil fue...     NONE
2  The actual rise in sea levels measured only 12...     NONE
3  Claims of global warming have been greatly exa...  AGAINST
4  The Intergovernmental Panel on Climate Change ...     NONE

In [ ]:
#Drop message column
df2 = df2.drop('message', axis=1)
print(df.head())

                                            sentence    label
0  Warmerthannormal sea surface temperatures are ...    FAVOR
1  We will continue to rely in part on fossil fue...     NONE
2  The actual rise in sea levels measured only 12...     NONE
3  Claims of global warming have been greatly exa...  AGAINST
4  The Intergovernmental Panel on Climate Change ...     NONE

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13973 entries, 0 to 11534
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  13973 non-null  object
 1   label     13973 non-null  object
dtypes: object(2)
memory usage: 327.5+ KB

In [ ]:
# check the label occurances
df2['label'].value_counts()

label
NONE       4885
FAVOR      4831
AGAINST    4257
Name: count, dtype: int64

In [ ]:
# Drop label NONE and FAVOR count to 4257 each ramdomly

# 1. Separate the categories into their own DataFrames
df_none = df2[df2['label'] == 'NONE']
df_favor = df2[df2['label'] == 'FAVOR']

# Keep all other labels (like 'AGAINST', etc.) completely untouched
df_others = df2[~df2['label'].isin(['NONE', 'FAVOR'])]

# 2. Randomly sample exactly 4,257 rows from NONE and FAVOR
# (random_state ensures your code produces the exact same random split every time)
df_none_sampled = df_none.sample(n=4257, random_state=42)
df_favor_sampled = df_favor.sample(n=4257, random_state=42)

# 3. Vertically concatenate everything back together
balanced_df = pd.concat([df_none_sampled, df_favor_sampled, df_others])

# 4. Shuffle the dataset so the rows aren't grouped by label
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
balanced_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12771 entries, 0 to 12770
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  12771 non-null  object
 1   label     12771 non-null  object
dtypes: object(2)
memory usage: 199.7+ KB

In [ ]:
balanced_df['label'].value_counts()

label
FAVOR      4257
AGAINST    4257
NONE       4257
Name: count, dtype: int64

In [ ]:
# download balanced df as csv
balanced_df.to_csv('English_train_data.csv', index=False)